### ISSUE TITLE
How can i use these module？

### ISSUE THREAD

**Issue by KevinBanksB** [pprp/awesome-attention-mechanism-in-cv#1]
Can you give a detailed tutorial on how to embed a module into the current semantic segmentation architecture（like fcn、unet）

**Comment by pprp** [comment]
Thank you for your interests in my project!

Most of these modules can function as plug-and-play modules. You can just plug in one of these 
modules as same as convolutions. For more examples, you can refer to repos in https://github.com/mrgloom/awesome-semantic-segmentation
