### ISSUE TITLE
关于Dense-and-implicit attention network (DIANet)

### ISSUE THREAD

**Issue by dedekinds** [pprp/awesome-attention-mechanism-in-cv#2]
您好，我是DIANet的作者。很高兴看到这个整理全面的repo。我对DIANet在readme上所给出的main idea有个简单的建议，我觉得DIANet的main idea不是简单的“LSTM+全程SE注意力”，而是“block间特征share”。我觉得改为“LSTM+block间特征share+通道注意力”会比较准确~谢谢Thanks♪(･ω･)ﾉ

**Comment by pprp** [comment]
@dedekinds 感谢您的建议，读的比较粗糙，没能get到精华。

已修正: https://github.com/pprp/awesome-attention-mechanism-in-cv/commit/a62472c955babb4c41596d4501bdcd5bb77df485

**Comment by dedekinds** [comment]
> @dedekinds 感谢您的建议，读的比较粗糙，没能get到精华。
> 
> 已修正: [a62472c](https://github.com/pprp/awesome-attention-mechanism-in-cv/commit/a62472c955babb4c41596d4501bdcd5bb77df485)

Thanks♪(･ω･)ﾉ
