### ISSUE TITLE
关于FcaNet: Frequency Channel Attention Networks

### ISSUE THREAD

**Issue by dedekinds** [pprp/awesome-attention-mechanism-in-cv#3]
Hi♪(･ω･)ﾉ，建议FcaNet: Frequency Channel Attention Networks的publish可以更新为ICCV2021~[[Link]](https://openaccess.thecvf.com/content/ICCV2021/papers/Qin_FcaNet_Frequency_Channel_Attention_Networks_ICCV_2021_paper.pdf)~

**Comment by pprp** [comment]
已修改，感谢提醒
