### ISSUE TITLE
Context-Gated Convolution

### ISSUE THREAD

**Issue by cenchaojun** [pprp/awesome-attention-mechanism-in-cv#4]
是不是可以建立一个关于awesome convolution的仓库呢，这个感觉也很有意思

**Comment by pprp** [comment]
May be [this repo](https://github.com/kaijieshi7/awesome-dynamic-convolution) can meet your requirements. 

IMO, Context-Gated Convolution belongs to both dynamic convolution and attention module.

You can refer to [this blog](https://zhuanlan.zhihu.com/p/354507714) to get more information about dynamic convolution.
